---
title: "Análise de cesta de Compras"
author: "Debora, Renato, Viviane"
date: "11/14/2020"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: lumen
runtime: shiny
---

```{r setup, include=FALSE, warning=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(readxl)
library(knitr)

library(outliers)
library(ggthemes)
library(skimr)
library(lubridate)
library(janitor)

library(arules)
library(arulesViz)

#library(devtools)
library(factoextra)

library(flexdashboard)
library(shiny)
library(highcharter)
library(viridisLite)


library(tidytext)
library(tidymodels)
library(tidyverse)

library(conflicted) 

conflict_prefer("filter", "dplyr")
#conflict_prefer("mutate", "dplyr")
#conflict_prefer("arrange", "dplyr")
#conflict_prefer("pivot_longer", "dplyr")
#conflict_prefer("starts_with", "dplyr")
#conflict_prefer("select", "dplyr")
#conflict_prefer("summarise", "dplyr")
#conflict_prefer("rename", "dplyr")
#conflict_prefer("across", "dplyr")
#conflict_prefer("group_by", "dplyr")


today <- Sys.Date()

theme_set(theme_minimal())
theme_update(text = element_text(family = "Open Sans", size = 16),
             plot.title = element_text(face = "bold", size = 18,
                                       color = "#1d3752"),
             legend.position = "bottom")

options(digits=4)

hc_cols <- c("#7cb5ec", "#434348", "#90ed7d", "#f7a35c", 
             "#8085e9", "#f15c80", "#e4d354", "#2b908f", 
             "#f45b5b", "#91e8e1")

```


```{r global, message=FALSE, warning=FALSE, cache=TRUE, context="data", include=FALSE}

# Data ---------

retail_raw <- read_csv("data/retail.csv")

retail <- retail_raw %>% 
  clean_names() %>%
  mutate(description = str_replace(description, ",","|")) %>% 
  mutate(month_year = as.Date(floor_date(date)),
         total_revenue = quantity * unit_price)

# Processamento ----------

rt_summary <- retail %>% 
  group_by(country) %>% 
  dplyr::summarise(across(c("quantity", "total_investment", "total_revenue"),
                   ~sum(.x, na.rm = T)),
                  across(c("unit_price", "nps"), ~mean(.x, na.rm = T)),
                  tkts = n_distinct(invoice_no)) %>% 
  mutate(perc_net = round(total_revenue*100/sum(total_revenue),1),
         perc_tkts = round(tkts*100/sum(tkts),1)) %>% 
  arrange(desc(total_revenue))

cols_map <- tibble(col = colnames(rt_summary %>% 
                                    select(where(is.numeric)) %>% 
                                    select(-starts_with("perc"))),
               name = c("Quantidade","Investimento Total","Receita Total", "Preço Unitário",
                        "NPS", "Ticket")) %>%  arrange(name)

# Análise UK ------------

group_tb <- tibble(group_name = c("Pedido", "Cliente", "Produto"),
                   col_name = c("invoice_no", "customer_id","description"))

tickets <- retail %>% 
  filter(country == "United Kingdom") %>% 
  group_by(invoice_no) %>%
  summarise(Quantidade = sum(quantity), Receita = sum(total_revenue)) %>% 
  arrange(desc(Receita))

foras <- tickets %>% 
  filter(Receita > 50000) %>%
  select(invoice_no) %>% unique() %>% 
  pull(invoice_no)

clientes <- retail %>% 
  group_by(customer_id,invoice_no) %>%
  summarise(Tkt = length(unique(invoice_no)) ,Qty = sum(quantity), Net = sum(total_revenue)) %>%
  group_by(customer_id) %>%
  summarise(Tkt = sum(Tkt) ,Qty = sum(Qty), Net = sum(Net)) %>%
  arrange(desc(Net))

foras2 <- clientes %>% 
  filter(Tkt > 100) %>% 
  pull(customer_id)

rt_uk_prep <- retail %>% 
  filter(country == "United Kingdom") %>% 
  filter(!invoice_no %in% foras) %>% 
  filter(!customer_id %in% foras2)

# Categorização --------------

colours <- str_c(str_to_upper(colors()), collapse="|")

numbers <- str_c(c("1","2","3","4","5","6","7","8","9","0"), collapse="|")

#stop_words <- str_c(get_stopwords()[1], collapse="|")
size <- str_c(str_to_upper(c('small', 'large', 'jumbo', 'box', 'pack', 'cases', 'kit')), collapse="|")
material <- str_c(str_to_upper(c('metal','wooden', 'wood', 'glass', 'silver', 'ceramic')), collapse="|")
stopword <- str_c(str_to_upper(c('set','of', 'with', 'and', 'colour')), collapse="|")

filters <- str_c(c(size, material, stopword, colours, numbers), collapse = "|")

rt_uk <- rt_uk_prep %>% 
  mutate(product = str_replace_all(description, filters,""),
         product = str_replace_all(product, "\\W", " "),
         product = str_replace_all(product, "\\s+$", ""),
         product = str_replace_all(product, "^\\s+", ""),
         product = str_replace_all(product, "\\s+", " "))
 

# Falta colocar para tirar espaço do inicio ou do final
  
#head(retail_2$Description_2,5)
#tail(retail_2$Description_2,5)

# PCA -------------

pca_prep <- rt_uk %>% 
   group_by(invoice_no, product) %>% 
   summarise(total_quantity = sum(quantity),.groups = "drop") %>% 
   arrange(total_quantity %>% desc()) %>%
   group_by(product) %>%
   mutate(total_quantity_description = sum(total_quantity)) %>% 
   arrange(total_quantity_description %>% desc()) %>% 
   ungroup() %>% 
   select(-total_quantity_description) %>% 
   pivot_wider(names_from = product,
              values_from = total_quantity,
              #values_fill = list(total_quantity = 0)
              values_fill = 0
              ) %>% #janitor::clean_names() %>% glimpse()
  #RC: alterei "values_fill = 0" por "values_fill = list(values = 0)"
     select(1:501)

rec_pca <- recipe( ~ ., data = pca_prep) %>% 
  update_role(invoice_no, new_role = "id") %>% 
  step_normalize(all_predictors()) %>% 
  step_pca(all_predictors(), id = "pca") %>% 
  prep()


tidy_pca <- rec_pca %>% 
  tidy(id = "pca")

#skim(tidy_pca)

# PCA para os top 500 produtos, selecionando apenas a componente com a maior contribuição

top_pca <- tidy_pca %>%
  select(-id) %>% 
  filter(component %in% paste0("PC", 1:20)) %>%
  group_by(component) %>%
  filter(value^2 > mean(value^2)) %>%
  ungroup() %>% 
  group_by(terms) %>% 
  top_n(1, abs(value)) %>% 
  ungroup() %>% 
  arrange(terms)

rt_pca <- rt_uk %>% 
  left_join(top_pca, by = c("product" ="terms")) %>% 
  filter(!is.na(component))

products_pca <- rt_pca %>% 
  group_by(component, product) %>% 
  summarise(across(c("quantity", "total_investment", "total_revenue"),
                   ~sum(.x, na.rm = T)),
                  across(c("unit_price", "nps"), ~mean(.x, na.rm = T)),
                  tkts = n_distinct(invoice_no)) %>% 
  top_n(20, total_revenue) %>% 
  arrange(desc(total_revenue)) %>% 
  ungroup()
  

pca_summary <- rt_pca %>% 
  group_by(component) %>% 
  summarise(across(c("quantity", "total_investment", "total_revenue"),
                   ~sum(.x, na.rm = T)),
                  across(c("unit_price", "nps"), ~mean(.x, na.rm = T)),
                  tkts = n_distinct(invoice_no),
                  products = n_distinct(product)) %>% 
  mutate(perc_net = round(total_revenue*100/sum(total_revenue),1),
         perc_tkts = round(tkts*100/sum(tkts),1)) %>% 
  filter(products > 1) %>% 
  arrange(desc(total_revenue)) %>% 
  top_n(20, total_revenue)
  #filter(total_revenue > mean(total_revenue)) %>% 
  #ungroup()

pca_drilldown <- products_pca %>%
  filter(component %in% pca_summary$component) %>% 
  group_nest(component) %>% 
  mutate(id = component,
    type = "column",
    # in the drilldown we'll give the mapping via creating the columns
    data = map(data, mutate, name = product, y = total_revenue),
    data = map(data, list_parse))

#skim(rt_pca)
  
# Análise Produtos -------------

prod_pca <- top_pca %>% 
  filter(component %in% paste0("PC", 5)) %>% 
  arrange(desc(value)) %>% 
  pull(terms)

rt_mission <- rt_uk %>% 
  filter(product %in% prod_pca) %>%
  mutate(month_year = as.Date(floor_date(date)),
         total_revenue = quantity * unit_price)


cols_prod <- tibble(col = c("avg_price","tkts" ,"clients",
                            "quantity", "total_investment", "total_revenue"),
               name = c("Preço Unitário","Pedidos","Clientes", "Quantidade",
                        "Investimento Total", "Receita Total")) %>% arrange(name)

# Basket Analysis --------------

#ibrary(plyr)

#processamento da base
#itemList <- ddply(rt_uk,c("customer_id","date"), 
#                  function(df1)paste(df1$product, 
#                                     collapse = ","))
#
#itemList$CustomerID <- NULL
#itemList$Date <- NULL
#colnames(itemList) <- c("items")
#
#write.csv(itemList,"output/market_basket.csv", quote = FALSE, row.names = TRUE)

#tr <- read.transactions('output/market_basket.csv', format = 'basket', sep=',')
#
##regras de associacao
#rules <- apriori(tr, parameter = list(sup = 0.002, conf = 0.8))
##inspect(head(rules, n = 10, by = c("confidence", "lift")))
#
##Filtrar as regras da missao de compra
##PRECISA ATUALIZAR O df1$nome PELA LISTA DE PRODUTOS FOCO NOSSA
#rules.sub <- subset(rules, subset = rhs %in% prod_pca & lift > 2 )
#rules.sub
#inspect(head(rules.sub, n = 30, by = c("confidence", "lift")))



# Recomendação --------------




```


Introdução
=====================================  

```{r echo=FALSE}

#Slide - Como aumentar as vendas?

```

```{r}





```


Análise Geral
=====================================  

Parâmetros {.sidebar}
-----------------------------------------------------------------------

```{r echo = FALSE}

selectInput("var_id", label = "Variável", choices = cols_map$name,
            multiple = F,
            selected = "Receita Total")

selectInput("group_id", label = "Agrupamento", choices = group_tb$group_name,
            multiple = F,
            selected = "Pedido")


actionButton("update_button", "Atualizar")


```


Row {.tabset}
-----------------------------------------------------------------------

### Mapa Geral

```{r echo=FALSE}

highchartOutput("sales_map")

```

```{r warning=FALSE, context="server"}

selected_col <- reactive({
  
    clicks <- input$update_button
  
  isolate({
  
    cols_map %>% 
      #filter(name == "Quantidade") %>% 
      filter(name == input$var_id) %>% 
      pull(col)
  
})})

output$sales_map <- renderHighchart({
  
  clicks <- input$update_button
  
isolate({  
  
  hcmap(
    "custom/world-robinson-lowres", 
    data = rt_summary,
    name = input$var_id, 
    #value = "total_revenue",
    value = selected_col(),
    borderWidth = 0,
    nullColor = "#d3d3d3",
    joinBy = c("name","country")) %>%
  hc_colorAxis(
    stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1, direction = -1)),
    type = "logarithmic") %>% 
  hc_tooltip(valueDecimals = 2)
  
  })})

```

### Faturamento e Transações por país

```{r echo = FALSE}

#highchartOutput("sales_pct")
#
#```
#
#```{r warning=FALSE, context="server"}
#
#output$sales_line <- renderHighchart({
  
  rt_summary %>%  
    select(country, starts_with("perc")) %>% 
    pivot_longer(cols = starts_with("perc"),
                 names_prefix = "perc_",
                 names_to = "variable",
                 values_to = "pct") %>% 
    mutate(variable = if_else(variable == "net","Faturamento", "Transações")) %>% 
    hchart(., "column", 
           hcaes(x = country, #reorder(country,desc(perc_net)), 
                 y = pct,
                 group = variable)) %>% 
    hc_xAxis(title = list(text = "País")) %>% 
    hc_yAxis(title = list(text = ""),
               labels = list(format = "{value}%"))
  
 # })

```

### Vendas por produto

```{r echo=FALSE}

rt_uk %>% 
  group_by(description) %>%
  summarise(Quantidade = sum(quantity), Receita = sum(total_revenue)) %>% 
  arrange(desc(Receita)) %>% kable()

```


### Distribuição por transação

```{r echo = FALSE}

#plotOutput("histogram")
#
#```
#
#
#```{r warning=FALSE, context="server"}
#
#selected_group <- reactive({
#  
#    clicks <- input$update_button
#  
#  isolate({
#  
#    group_tb %>% 
#      #filter(name == "Quantidade") %>% 
#      filter(group_name == input$group_id) %>% 
#      pull(col_name)
#  
#})})
#
#
#output$histogram <- renderPlot({
  
#  clicks <- input$update_button
#  
#isolate({ 
#
#  retail %>% 
#    filter(country == "United Kingdom") %>% 
#    group_by(selected_group()) %>% 
#    summarise(Total = sum(select_col())) %>% 
#      ggplot(aes(x = Total)) + 
#      geom_histogram(binwidth = 50) + 
#      coord_cartesian(xlim = c(0, 2000))+
#      geom_vline(aes(xintercept=median(Total)),
#                color = hc_cols[1], linetype="dashed", size=1)+
#      geom_vline(aes(xintercept=mean(Total)),
#                color="red", linetype="dashed", size=1) +
#      labs(title = "Produtos por transação", x = "Quantidade de produtos", y = "")
    

tickets %>% 
   pivot_longer(cols = c("Quantidade","Receita"),
                names_to = "variable",
                values_to = "value") %>% 
   group_by(variable) %>% 
 ggplot(aes(x=value)) + 
 geom_histogram(binwidth=50) + 
 coord_cartesian(xlim = c(0, 2000))+
 geom_vline(aes(xintercept=median(value)),
           color = hc_cols[1], linetype="dashed", size=1)+
 geom_vline(aes(xintercept=mean(value)),
           color="red", linetype="dashed", size=1) +
   facet_wrap(~variable, nrow = 2, scales = "free_y") +
 labs(title = "Produtos por transação", x = "Quantidade de produtos", y = "")
 
#})
#})

```


### Preços

```{r}

plotOutput("histogram")

```

```{r warning=FALSE, context="server"}

selected_col <- reactive({
  
    clicks <- input$update_button
  
  isolate({
  
    cols_map %>% 
      #filter(name == "Quantidade") %>% 
      filter(name == input$var_id) %>% 
      pull(col)
  
})})

output$histogram <- renderPlot({
  
  clicks <- input$update_button
  
isolate({ 
  
retail %>% 
ggplot(aes(x = unit_price)) + 
  geom_histogram(binwidth = 1) + coord_cartesian(xlim = c(0, 20))+
  geom_vline(aes(xintercept=median(unit_price)),
            color="blue", linetype="dashed", size=1) +
   geom_vline(aes(xintercept=mean(unit_price)),
            color="red", linetype="dashed", size=1) +
  #theme_economist() +
  labs(title = "Preço por Produto",x = "Preço", y = "Produto")

})})
 
```


### PCA 

```{r}

highchartOutput2("drilldown")

```


```{r warning=FALSE, context="server"}


output$drilldown <- renderHighchart2({
  
x <- c("Receita Total (MM)", "Itens", "Pedidos (%)")
y <- c("{point.total_revenue}", "{point.quantity}", "{point.perc_tkts}%")

tt <- tooltip_table(x, y)

hchart(
  pca_summary,
  "column",
  hcaes(x = component, y = total_revenue, 
        name = component, drilldown = component),
  name = "Components",
  #colorByPoint = TRUE
) %>% 
  hc_drilldown(
    allowPointDrilldown = TRUE,
    series = list_parse(pca_drilldown)
  ) %>% 
  hc_tooltip(
    pointFormat = tt, # "{point.name} {point.pop}"
    useHTML = TRUE,
    valueDecimals = 0
  ) %>% 
  hc_yAxis(
    title = list(text = "Receita total (log scale)"),
    #type = "logarithmic",
    minorTickInterval = 'auto'
  ) %>% 
  hc_xAxis(
    title = ""
  )
  
  
})


```


Missão
=====================================  

Parâmetros {.sidebar}
-----------------------------------------------------------------------

```{r echo=FALSE}


#selectInput("component_2", label = "Componente", choices = pca_summary$component,
#            multiple = F,
#            selected =  paste0("PC", 5))


selectInput("var_id_2", label = "Variável", choices = cols_prod$name,
            multiple = F,
            selected = cols_prod$name[5])

#uiOutput("products_in")

 selectInput("prod_id", label = "Selecione o produto", 
                choices = append("ALL", prod_pca),
            multiple = T,
            selected = "ALL")

actionButton("update_button_2", "Atualizar")


```


```{r warning=FALSE, context="server"}

#products_reactive <- reactive({
#  
#  top_pca %>% 
#  filter(component %in% input$component_id) %>% 
#  arrange(desc(value)) %>% 
#  pull(terms)
#
#})
#
#
#output$products_in <- renderUI({
#  
#    
#    selectInput("prod_id", label = "Selecione o produto", 
#                choices = append("ALL", products_reactive()),
#            multiple = T,
#            selected = "ALL")
#    
#})

selected_products <- reactive({
  
  clicks <- input$update_button_2
  
isolate({  
  
 #if("ALL" %in% input$prod_id){products_reactive()}else{input$prod_id}
  
  if("ALL" %in% input$prod_id){prod_pca}else{input$prod_id}
  
  
 #if("ALL" %in% prod_list){products}else{prod_list}
  
})})

selected_col_2 <- reactive({
  
    clicks <- input$update_button_2
  
  isolate({
  
    
    cols_prod %>% 
      #filter(name == "Quantidade") %>% 
      filter(name == input$var_id_2) %>% 
      pull(col)
    
  
})})



#rt_mission_reactive <- reactive({
#  
# clicks <- input$update_button_2
#  
#  isolate({ 
#  
#  
#  rt_uk %>% 
#  filter(product %in% products_reactive()) %>%
#  mutate(month_year = as.Date(floor_date(date)),
#         total_revenue = quantity * unit_price)
#  
#})})
#
```


Row
-----------------------------------------------------------------------

### Dias da semana 

```{r echo = FALSE}

plotOutput("days_chart")

```

### Feriados

```{r echo = FALSE}

plotOutput("holiday_chart")

```


```{r warning=FALSE, context="server"}


rt_days <- reactive({
  
  clicks <- input$update_button_2
  
isolate({  

rt_mission %>% 
   mutate(dow = wday(date, label = T, abbr = T),
          full_hour = hour(time),
          holiday = as.factor(holiday)) %>% 
  filter(product %in% selected_products()) %>%
  group_by(dow, full_hour, holiday) %>% 
  dplyr::summarise(unit_price = sum(unit_price * quantity)/sum(quantity),
            tkts = n_distinct(invoice_no),
            clients = n_distinct(customer_id),
            nps = mean(nps),
            across(c("quantity", "total_investment", "total_revenue"),
                   ~sum(.x, na.rm = T)))
})})

output$days_chart <- renderPlot({
  
    clicks <- input$update_button_2
  
isolate({  
  
col <- selected_col_2()

print(col)
  
rt_days() %>% 
  filter(holiday == 0) %>% 
  ggplot(aes(x = dow, y = full_hour, fill = get(selected_col_2()))) +
  geom_tile() +
  scale_fill_viridis_c(labels = scales::label_number_si()) +
  labs(x = "", y = "Hora", title = "Dias Normais", fill = input$var_id_2)
  })
})


output$holiday_chart <- renderPlot({
  
    clicks <- input$update_button_2
  
isolate({  
  
rt_days() %>% 
  filter(holiday == 1) %>% 
  ggplot(aes(x = dow, y = full_hour, fill = get(selected_col_2()))) +
  geom_tile() +
  scale_fill_viridis_c(labels = scales::label_number_si()) +
  labs(x = "", y = "Hora", title = "Feriados", fill = input$var_id_2)
  })
})

```


Row
-----------------------------------------------------------------------

### Evolução

```{r echo =FALSE}


plotOutput("sales_line")

```


```{r warning=FALSE, context="server"}

output$sales_line <- renderPlot({
  
  clicks <- input$update_button_2
  
isolate({  
  
acc_prod <- rt_mission %>% 
  filter(product %in% selected_products()) %>%
  group_by(month_year) %>%
  arrange(month_year) %>% 
  select(month_year, product, everything()) %>% 
  summarise(unit_price = sum(unit_price * quantity)/sum(quantity),
            tkts = n_distinct(invoice_no),
            clients = n_distinct(customer_id),
            nps = mean(nps),
            across(c("quantity", "total_investment", "total_revenue"), ~sum(.x, na.rm = T))) %>% 
  mutate(acc_quantity = cumsum(quantity),
         acc_total_investment = cumsum(total_investment),
         acc_total_revenue = cumsum(total_revenue),
         acc_clients = cumsum(clients),
         acc_tkts = cumsum(tkts),
         acc_nps = nps,
         acc_unit_price = unit_price)
    
col <- paste0("acc_", selected_col_2())

acc_prod %>% 
   ggplot(aes(x = month_year, 
              #y = acc_total_revenue, 
              y = get(col), 
              )) +
   geom_line() + labs(y = input$var_id_2, x = "")
   
 #prod_summary() %>%  
 #  hchart(., "line", 
 #         hcaes(x = month_year, 
 #               y = selected,
 #               group = description,
 #               y = quantity
 #               )) %>% 
 #  hc_xAxis(title = list(text = "Data")) #%>% hc_yAxis(title = list(text = input$var_id))
 # 
  })})

```

Regras de Associação
=====================================  

Row {.tabset}
-----------------------------------------------------------------------

### Rede de Produtos

```{r echo = FALSE}

#Grafico ARULES
#plot(rules.sub,
#     engine = 'visNetwork',
#     method = 'graph')
#     #control = list(nodeCol='darkblue'))
#
```



```{r warning=FALSE, context="server"}

##Filtrar as regras da missao de compra
#PRECISA ATUALIZAR O df1$nome PELA LISTA DE PRODUTOS FOCO NOSSA
#rules.sub <- subset(rules, subset = rhs %in% prod_pca & lift > 2 )
#rules.sub
#inspect(head(rules.sub, n = 30, by = c("confidence", "lift")))


```

Row {.tabset}
-----------------------------------------------------------------------

```{r}

```


Recomendação
=====================================  

Row {.sidebar}
-----------------------------------------------------------------------

### Selecione os produtos

```{r}

```


Row {.tabset}
-----------------------------------------------------------------------

### Resultados

```{r}



```






